"""Add token usage and source docs to ChatHistory

Revision ID: 223c8c8315e8
Revises: f35803229a70
Create Date: 2025-02-10 14:40:49.937262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223c8c8315e8'
down_revision: Union[str, None] = 'f35803229a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('source_docs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'source_docs')
    op.drop_column('chat_history', 'output_tokens')
    op.drop_column('chat_history', 'input_tokens')
    # ### end Alembic commands ###
