"""Add number_of_tokens to UsageToken

Revision ID: 902634df93e2
Revises: 223c8c8315e8
Create Date: 2025-02-17 20:42:18.627906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902634df93e2'
down_revision: Union[str, None] = '223c8c8315e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_tokens',
        sa.Column('number_of_tokens', sa.Integer(), 
                  server_default='1000',    # <-- add default
                  nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_tokens', 'number_of_tokens')
    # ### end Alembic commands ###
