"""Add input_tokens_used and output_tokens_used

Revision ID: ca92b287d82f
Revises: bf621a40ac9f
Create Date: 2025-02-06 20:37:49.327379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca92b287d82f'
down_revision: Union[str, None] = 'bf621a40ac9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
