"""Add api_key and demo_message_count to Chatbot

Revision ID: f4ec767ecc37
Revises: f4dc26433fd8
Create Date: 2025-01-08 16:23:52.961607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ec767ecc37'
down_revision: Union[str, None] = 'f4dc26433fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('chatbots', 
    sa.Column('demo_message_count', sa.Integer(), 
              server_default='0',    # This ensures existing rows are 0
              nullable=False))
    op.create_index(op.f('ix_chatbots_api_key'), 'chatbots', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbots_api_key'), table_name='chatbots')
    op.drop_column('chatbots', 'demo_message_count')
    op.drop_column('chatbots', 'api_key')
    # ### end Alembic commands ###
